### ISSUE TITLE
How to run chimg against a qcow2 image?

### ISSUE THREAD

**Issue by catmsred** [canonical/chimg#14]
I am attempting to run one of the example config files (https://github.com/canonical/chimg/blob/main/docs/config-samples/config-deb-only.yaml) against an existing image.  My process is:

Mount `${IMAGE_TO_MOUNT}` which is a qcow2 image:
```
MOUNTPOINT="./mount"
DEVICE_TO_CONNECT="nbd0"
ABS_MOUNT_PATH=$(realpath ${MOUNTPOINT})
mkdir -p ${MOUNTPOINT}
sudo modprobe nbd
sudo qemu-img info ${IMAGE_TO_MOUNT}
sudo qemu-nbd -c /dev/${DEVICE_TO_CONNECT} ${IMAGE_TO_MOUNT}
sudo kpartx -a -v /dev/${DEVICE_TO_CONNECT}
sudo mount /dev/mapper/${DEVICE_TO_CONNECT}p1 ${ABS_MOUNT_PATH}
```

Run chimg:
```
$ sudo chimg --log-console chrootfs config-deb-only.yaml ~/code/chimg/mount/
2024-08-15 11:45:04,855:chimg.chroot:INFO:Setup mount points ...
2024-08-15 11:45:04,856:chimg.common:INFO:Running command: mount dev-live /home/catred/code/chimg/mount/dev -t devtmpfs
2024-08-15 11:45:04,858:chimg.common:INFO:Running command: mount devpts-live /home/catred/code/chimg/mount/dev/pts -t devpts -o nodev,nosuid
2024-08-15 11:45:04,860:chimg.common:INFO:Running command: mount proc-live /home/catred/code/chimg/mount/proc -t proc
2024-08-15 11:45:04,861:chimg.common:INFO:Running command: mount sysfs-live /home/catred/code/chimg/mount/sys -t sysfs
2024-08-15 11:45:04,863:chimg.common:INFO:Running command: mount securityfs /home/catred/code/chimg/mount/sys/kernel/security -t securityfs
2024-08-15 11:45:04,866:chimg.common:INFO:Running command: mount none /home/catred/code/chimg/mount/sys/fs/cgroup -t cgroup2
2024-08-15 11:45:04,869:chimg.common:INFO:Running command: mount none /home/catred/code/chimg/mount/tmp -t tmpfs
2024-08-15 11:45:04,872:chimg.common:INFO:Running command: mount none /home/catred/code/chimg/mount/var/lib/apt/lists -t tmpfs
2024-08-15 11:45:04,874:chimg.common:INFO:Running command: mount none /home/catred/code/chimg/mount/var/cache/apt -t tmpfs
2024-08-15 11:45:04,876:chimg.chroot:INFO:mount points setup done
2024-08-15 11:45:04,876:chimg.common:INFO:Running command: /usr/sbin/chroot /home/catred/code/chimg/mount apt-get update --assume-yes --error-on=any
2024-08-15 11:50:25,252:chimg.common:ERROR:Command failed with return code 100 (success codes are: [0])
2024-08-15 11:50:25,252:chimg.common:ERROR:Env: {'DEBIAN_FRONTEND': 'noninteractive'}
2024-08-15 11:50:25,252:chimg.common:ERROR:Cwd: None
2024-08-15 11:50:25,252:chimg.common:ERROR:Stdout: Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:3 http://ppa.launchpad.net/cloud-images/gke-1.31-proposed/ubuntu jammy InRelease
Ign:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://ppa.launchpad.net/cloud-images/gke-1.31-proposed/ubuntu jammy InRelease
Ign:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:3 http://ppa.launchpad.net/cloud-images/gke-1.31-proposed/ubuntu jammy InRelease
Ign:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:6 http://archive.ubuntu.com/ubuntu jammy-proposed InRelease
Err:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://ppa.launchpad.net/cloud-images/gke-1.31-proposed/ubuntu jammy InRelease
  Temporary failure resolving 'ppa.launchpad.net'
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:6 http://archive.ubuntu.com/ubuntu jammy-proposed InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:6 http://archive.ubuntu.com/ubuntu jammy-proposed InRelease
Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:6 http://archive.ubuntu.com/ubuntu jammy-proposed InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...

2024-08-15 11:50:25,252:chimg.common:ERROR:Stderr: E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
E: Failed to fetch http://ppa.launchpad.net/cloud-images/gke-1.31-proposed/ubuntu/dists/jammy/InRelease  Temporary failure resolving 'ppa.launchpad.net'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-proposed/InRelease  Temporary failure resolving 'archive.ubuntu.com'
E: Some index files failed to download. They have been ignored, or old ones used instead.

2024-08-15 11:50:25,253:chimg.common:INFO:Running command: umount /home/catred/code/chimg/mount/var/cache/apt
2024-08-15 11:50:25,259:chimg.common:INFO:Running command: umount /home/catred/code/chimg/mount/var/lib/apt/lists
2024-08-15 11:50:25,262:chimg.common:INFO:Running command: umount /home/catred/code/chimg/mount/tmp
2024-08-15 11:50:25,264:chimg.common:INFO:Running command: umount /home/catred/code/chimg/mount/sys/fs/cgroup
2024-08-15 11:50:25,266:chimg.common:INFO:Running command: umount /home/catred/code/chimg/mount/sys/kernel/security
2024-08-15 11:50:25,268:chimg.common:INFO:Running command: umount /home/catred/code/chimg/mount/sys
2024-08-15 11:50:25,271:chimg.common:INFO:Running command: umount /home/catred/code/chimg/mount/proc
2024-08-15 11:50:25,273:chimg.common:INFO:Running command: umount /home/catred/code/chimg/mount/dev/pts
2024-08-15 11:50:25,276:chimg.common:INFO:Running command: umount /home/catred/code/chimg/mount/dev
Traceback (most recent call last):
  File "/snap/chimg/58/bin/chimg", line 8, in <module>
    sys.exit(main())
  File "/snap/chimg/58/lib/python3.10/site-packages/chimg/cli/__init__.py", line 74, in main
    args.func(args)
  File "/snap/chimg/58/lib/python3.10/site-packages/chimg/cli/__init__.py", line 33, in _chrootfs
    chroot.apply()
  File "/snap/chimg/58/lib/python3.10/site-packages/chimg/chroot.py", line 34, in apply
    [stack.enter_context(s) for s in stacks]
  File "/snap/chimg/58/lib/python3.10/site-packages/chimg/chroot.py", line 34, in <listcomp>
    [stack.enter_context(s) for s in stacks]
  File "/snap/chimg/58/usr/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/snap/chimg/58/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/snap/chimg/58/lib/python3.10/site-packages/chimg/chroot.py", line 518, in _ppas_setup
    self._apt_update()
  File "/snap/chimg/58/lib/python3.10/site-packages/chimg/chroot.py", line 328, in _apt_update
    run_command(
  File "/snap/chimg/58/lib/python3.10/site-packages/chimg/common.py", line 29, in run_command
    raise subprocess.CalledProcessError(result.returncode, cmd)
subprocess.CalledProcessError: Command '['/usr/sbin/chroot', '/home/catred/code/chimg/mount', 'apt-get', 'update', '--assume-yes', '--error-on=any']' returned non-zero exit status 100.
```

Is there a preferred way to convert a qcow2 image into a chroot so that it will be acceptable to chimg?

**Comment by rthill91** [comment]
If you're doing this manually you likely don't have a valid `/etc/resolv.conf` in the chroot. Mount your image exactly as you are and copy your host `/etc/resolv.conf` into the chroot (probably want to backup the chroot version somewhere like `{chroot}/etc/resolve.conf.bak` first and restore after your modifications).

**Comment by catmsred** [comment]
That resolved it, thanks!
